FROM quay.io/keycloak/keycloak:26.3.1 as builder

WORKDIR /opt/keycloak

RUN kc.sh build

FROM quay.io/keycloak/keycloak:26.3.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/

RUN microdnf install -y wget && microdnf clean all

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

CMD ["start", "--optimized"]
