'use client';

import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { analyzeContent, type AnalyzeContentOutput } from '@/ai/flows/analyze-content-generation';
import { Loader2, Lightbulb, Smile, Frown, Meh } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

export default function AiAnalysisPage() {
  const [content, setContent] = useState('');
  const [result, setResult] = useState<AnalyzeContentOutput | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async () => {
    if (!content.trim()) {
      setError('Content cannot be empty.');
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const analysisResult = await analyzeContent({
        content: content,
        contentType: 'User Feedback',
      });
      setResult(analysisResult);
    } catch (e) {
      console.error(e);
      setError('Failed to analyze content. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const getSentimentIcon = (sentiment: string) => {
    switch (sentiment.toLowerCase()) {
      case 'positive':
        return <Smile className="h-6 w-6 text-green-500" />;
      case 'negative':
        return <Frown className="h-6 w-6 text-red-500" />;
      default:
        return <Meh className="h-6 w-6 text-yellow-500" />;
    }
  };

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <h1 className="font-headline text-3xl font-bold tracking-tight">AI Content Analysis</h1>
        <p className="text-muted-foreground">
          Analyze user-generated content to understand sentiment, identify key topics, and get suggestions.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Content Input</CardTitle>
            <CardDescription>Enter the text you want to analyze.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <Textarea
                placeholder="E.g., 'The new tournament system is amazing, but I wish there were more prize options.'"
                className="min-h-[200px]"
                value={content}
                onChange={(e) => setContent(e.target.value)}
                disabled={loading}
              />
              {error && (
                 <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertTitle>Error</AlertTitle>
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}
              <Button onClick={handleAnalyze} disabled={loading} className="w-full">
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  'Analyze Content'
                )}
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Analysis Results</CardTitle>
            <CardDescription>Insights generated by the AI assistant.</CardDescription>
          </CardHeader>
          <CardContent className="min-h-[268px]">
            {loading && (
              <div className="flex h-full items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
              </div>
            )}
            {!loading && !result && (
              <div className="flex h-full items-center justify-center text-center text-muted-foreground">
                <Lightbulb className="mb-2 h-8 w-8" />
                <p>Your analysis results will appear here.</p>
              </div>
            )}
            {result && (
              <div className="space-y-6">
                <div>
                  <h3 className="mb-2 text-lg font-semibold">Sentiment</h3>
                  <div className="flex items-center gap-2">
                    {getSentimentIcon(result.sentiment)}
                    <span className="font-medium capitalize">{result.sentiment}</span>
                  </div>
                </div>
                <div>
                  <h3 className="mb-2 text-lg font-semibold">Key Topics</h3>
                  <div className="flex flex-wrap gap-2">
                    {result.keyTopics.map((topic) => (
                      <Badge key={topic} variant="secondary">{topic}</Badge>
                    ))}
                  </div>
                </div>
                <div>
                  <h3 className="mb-2 text-lg font-semibold">Suggested Improvements</h3>
                  <p className="text-sm text-muted-foreground">{result.suggestedImprovements}</p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// Dummy icon for compilation
const AlertCircle = (props: React.SVGProps<SVGSVGElement>) => <svg {...props}><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
