export const venuesList = [
  {
    id: 'venue-1',
    name: 'Футбольное поле "Центральное"',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'football field aerial',
    address: 'ул. Центральная, 1, Москва',
    surfaceType: 'Искусственный газон',
    rating: 4.8,
    price: '1500 ₽/час',
    features: ['Душевые', 'Раздевалки', 'Освещение'],
  },
  {
    id: 'venue-2',
    name: 'Баскетбольная площадка "Стритбол"',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'basketball court city',
    address: 'Парк "Южный", Москва',
    surfaceType: 'Резиновое покрытие',
    rating: 4.5,
    price: 'Бесплатно',
    features: ['Освещение'],
  },
  {
    id: 'venue-3',
    name: 'Волейбольная площадка "Пляж"',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'beach volleyball',
    address: 'Набережная реки, Москва',
    surfaceType: 'Песок',
    rating: 4.2,
    price: '500 ₽/час',
    features: ['Раздевалки'],
  },
  {
    id: 'venue-4',
    name: 'Теннисный корт "Академия"',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'tennis court',
    address: 'ул. Спортивная, 10, Москва',
    surfaceType: 'Грунт',
    rating: 4.9,
    price: '2000 ₽/час',
    features: ['Душевые', 'Раздевалки', 'Освещение', 'Прокат инвентаря'],
  },
];

export const myBookings = [
    {
        id: 'booking-1',
        venueName: 'Футбольное поле "Центральное"',
        date: '28 сентября 2024',
        time: '19:00 - 20:00',
        status: 'Подтверждено' as const,
    },
    {
        id: 'booking-2',
        venueName: 'Теннисный корт "Академия"',
        date: '22 сентября 2024',
        time: '10:00 - 12:00',
        status: 'Завершено' as const,
    },
    {
        id: 'booking-3',
        venueName: 'Баскетбольная площадка "Стритбол"',
        date: '15 сентября 2024',
        time: '18:00 - 19:00',
        status: 'Отменено' as const,
    }
];
