export const teamSports = [
  { id: 'team_football_01', name: 'Футбол' },
  { id: 'team_minifootball_02', name: 'Мини-футбол (футзал)' },
  { id: 'team_basketball_03', name: 'Баскетбол' },
  { id: 'team_volleyball_04', name: 'Волейбол' },
  { id: 'team_handball_05', name: 'Гандбол' },
  { id: 'team_hockey_06', name: 'Хоккей' },
  { id: 'team_bandy_07', name: 'Хоккей с мячом' },
  { id: 'team_waterpolo_08', name: 'Водное поло' },
  { id: 'team_rugby_09', name: 'Регби' },
  { id: 'team_lapta_10', name: 'Лапта' },
  { id: 'team_baseball_11', name: 'Бейсбол' },
  { id: 'team_softball_12', name: 'Софтбол' },
  { id: 'team_americanfootball_13', name: 'Американский футбол' },
  { id: 'team_beachvolleyball_14', name: 'Пляжный волейбол' },
  { id: 'team_beachfootball_15', name: 'Пляжный футбол' },
  { id: 'team_cricket_16', name: 'Крикет' },
  { id: 'team_floorball_17', name: 'Флорбол' },
  { id: 'team_ultimate_18', name: 'Ультимейт (фрисби)' },
  { id: 'team_beachhandball_19', name: 'Пляжный гандбол' },
  { id: 'team_curling_20', name: 'Кёрлинг' },
  { id: 'team_cheerleading_21', name: 'Чирлидинг' },
  { id: 'team_esports_22', name: 'Киберспорт (командный)' },
  { id: 'team_fieldhockey_23', name: 'Хоккей на траве' },
  { id: 'team_square_24', name: 'Квадрат (детский)' },
  { id: 'team_badminton_25', name: 'Бадминтон (парный/командный)' },
  { id: 'team_petanque_26', name: 'Петанк' },
];

export const individualSports = [
  { id: 'solo_athletics_101', name: 'Лёгкая атлетика' },
  { id: 'solo_tennis_102', name: 'Теннис' },
  { id: 'solo_tabletennis_103', name: 'Настольный теннис' },
  { id: 'solo_badminton_104', name: 'Бадминтон (одиночный)' },
  { id: 'solo_boxing_105', name: 'Бокс' },
  { id: 'solo_fencing_106', name: 'Фехтование' },
  { id: 'solo_swimming_107', name: 'Плавание' },
  { id: 'solo_cycling_108', name: 'Велоспорт' },
  { id: 'solo_triathlon_109', name: 'Триатлон' },
  { id: 'solo_gymnastics_110', name: 'Спортивная гимнастика' },
  { id: 'solo_trampoline_111', name: 'Прыжки на батуте' },
  { id: 'solo_skiing_112', name: 'Лыжные гонки' },
  { id: 'solo_snowboard_113', name: 'Сноуборд' },
  { id: 'solo_skating_114', name: 'Конькобежный спорт' },
  { id: 'solo_biathlon_115', name: 'Биатлон' },
  { id: 'solo_weightlifting_116', name: 'Тяжёлая атлетика' },
  { id: 'solo_powerlifting_117', name: 'Пауэрлифтинг' },
  { id: 'solo_judo_118', name: 'Дзюдо' },
  { id: 'solo_karate_119', name: 'Карате' },
  { id: 'solo_taekwondo_120', name: 'Тхэквондо' },
  { id: 'solo_sambo_121', name: 'Самбо' },
  { id: 'solo_wrestling_122', name: 'Борьба' },
  { id: 'solo_esports_123', name: 'Киберспорт (личный)' },
  { id: 'solo_skateboarding_124', name: 'Скейтбординг' },
  { id: 'solo_surfing_125', name: 'Серфинг' },
  { id: 'solo_orienteering_126', name: 'Спортивное ориентирование' },
  { id: 'solo_golf_127', name: 'Гольф' },
  { id: 'solo_chess_128', name: 'Шахматы' },
  { id: 'solo_checkers_129', name: 'Шашки' },
  { id: 'solo_billiards_130', name: 'Бильярд' },
  { id: 'solo_darts_131', name: 'Дартс' },
  { id: 'solo_armwrestling_132', name: 'Армрестлинг' },
  { id: 'solo_streetlifting_133', name: 'Стритлифтинг' },
  { id: 'solo_streetball_134', name: 'Стритбол (1x1)' },
  { id: 'solo_climbing_135', name: 'Скалолазание' },
  { id: 'solo_sumo_136', name: 'Сумо' },
  { id: 'solo_diving_137', name: 'Прыжки в воду' },
  { id: 'solo_shooting_138', name: 'Стрельба (лук, пневматика)' },
  { id: 'solo_sailing_139', name: 'Парусный спорт' },
];
