export const teams = [
  {
    name: 'Кибер Орлы',
    motto: 'Выше всех, быстрее всех, сильнее всех!',
    logo: 'https://placehold.co/128x128.png',
    dataAiHint: 'eagle logo',
    captain: "Alex 'CyberSlasher' Doe",
    rank: 1,
    members: 5,
    slug: 'cyber-eagles',
  },
  {
    name: 'Ледяные Драконы',
    motto: 'Холодный расчет, пламенный удар.',
    logo: 'https://placehold.co/128x128.png',
    dataAiHint: 'dragon logo',
    captain: 'Frosty',
    rank: 2,
    members: 5,
    slug: '#',
  },
  {
    name: 'Вихревые Гадюки',
    motto: 'Жалим быстро, побеждаем тихо.',
    logo: 'https://placehold.co/128x128.png',
    dataAiHint: 'snake logo',
    captain: "Jane 'Venom' Doe",
    rank: 3,
    members: 5,
    slug: '#',
  },
  {
    name: 'Квантовые Квазары',
    motto: 'За пределами понимания.',
    logo: 'https://placehold.co/128x128.png',
    dataAiHint: 'galaxy logo',
    captain: "Alex 'Nova' Ray",
    rank: 4,
    members: 4,
    slug: '#',
  },
  {
    name: 'Стальные Титаны',
    motto: 'Несокрушимая воля, стальной характер.',
    logo: 'https://placehold.co/128x128.png',
    dataAiHint: 'robot titan',
    captain: "Max 'Titan' Iron",
    rank: 5,
    members: 5,
    slug: '#',
  },
];
