export const userList = [
  { id: 'usr-admin-1', name: 'Admin User', email: 'admin.user@prodvor.com', role: 'Администратор', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/administrator', activitySummary: 'Высокоуровневые административные действия, управление пользователями, конфигурация системы. Низкое взаимодействие с сообществом.' },
  { id: 'usr-mod-1', name: 'Модератор Макс', email: 'max.mod@prodvor.com', role: 'Модератор', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/moderator', activitySummary: 'Активен в модерации чата, разрешает жалобы пользователей, выдает предупреждения. Постоянно онлайн в часы пик.' },
  { id: 'usr-mod-2', name: 'Елена Модератова', email: 'elena.m@prodvor.com', role: 'Модератор', status: 'На смене', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/moderator', activitySummary: 'Специализируется на разрешении споров по матчам. Недавно прошла дополнительное обучение по правилам платформы.' },
  { id: 'usr-player-1', name: "Alex 'CyberSlasher' Doe", email: 'alex.doe@prodvor.com', role: 'Капитан', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/player', activitySummary: 'Регулярно участвует в матчах, активен в командном чате, организует тренировки. Чистая история, без серьезных жалоб.' },
  { id: 'usr-player-2', name: "Maria 'Shadow' Petrova", email: 'maria.p@prodvor.com', role: 'Игрок', status: 'Забанен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/player', activitySummary: 'История токсичного поведения в чате, множественные жалобы от других пользователей, подозрение в использовании нечестных тактик.' },
  { id: 'usr-player-3', name: "Иван 'Beast' Орлов", email: 'ivan.o@prodvor.com', role: 'Игрок', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/player', activitySummary: 'Известен своей помощью новичкам в чате. Часто делится полезными советами и тактиками.' },
  { id: 'usr-judge-1', name: 'Судья Джуди', email: 'judy.j@prodvor.com', role: 'Судья', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/judge', activitySummary: 'Председательствовала на многочисленных официальных матчах, известна справедливыми и своевременными решениями. Высокий рейтинг от капитанов команд.' },
  { id: 'usr-manager-1', name: 'Джерри Магуайр', email: 'jerry.m@prodvor.com', role: 'Менеджер', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/manager', activitySummary: 'Управляет составом команды, ведет переговоры со спонсорами, занимается финансами команды. Активность в основном в приватных каналах.' },
  { id: 'usr-org-1', name: 'Event Horizon Inc.', email: 'events@horizon.com', role: 'Организатор', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/organizer', activitySummary: 'Успешно организовано три турнира в этом сезоне. Управляет сетками, расписаниями и коммуникациями с участниками.' },
  { id: 'usr-sponsor-1', name: 'Sponsor Corp', email: 'contact@sponsorcorp.com', role: 'Спонсор', status: 'Проверен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/sponsor', activitySummary: 'Активность связана с рекламными кампаниями и переводами средств командам и турнирам.' },
  { id: 'usr-fan-1', name: 'Верный Ларри', email: 'larry.fan@prodvor.com', role: 'Болельщик', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/fan', activitySummary: 'Часто комментирует матчи, активен в чатах болельщиков, высокая вовлеченность в посты. Положительные отзывы.' },
  { id: 'usr-fan-2', name: 'Фанат Федор', email: 'fedor.fan@prodvor.com', role: 'Болельщик', status: 'Активен', avatar: 'https://placehold.co/40x40.png', profileUrl: '/administration/fan', activitySummary: 'Активность в основном заключается в поддержке одной команды. Иногда вступает в споры в чатах.' },
];
