

export const matchesList = [
    {
        id: '1',
        team1: { name: 'Кибер Орлы', logo: 'https://placehold.co/100x100.png', logoHint: 'eagle logo' },
        team2: { name: 'Ледяные Волки', logo: 'https://placehold.co/100x100.png', logoHint: 'wolf logo' },
        score: '13-10',
        tournament: 'Летний Старт 2024',
        game: 'Valorant',
        date: '2024-07-26',
        status: 'Завершен',
        href: '/matches/123',
        playgroundId: null,
    },
    {
        id: '2',
        team1: { name: 'Теневые Лисы', logo: 'https://placehold.co/100x100.png', logoHint: 'fox logo' },
        team2: { name: 'Стальные Титаны', logo: 'https://placehold.co/100x100.png', logoHint: 'titan logo' },
        score: 'Live',
        tournament: 'Лига ProDvor',
        game: 'Valorant',
        date: '2024-07-29',
        status: 'Идет',
        href: '/matches/123',
        playgroundId: null,
    },
    {
        id: '3',
        team1: { name: 'Соколы', logo: 'https://placehold.co/100x100.png', logoHint: 'falcon logo' },
        team2: { name: 'Торпедо', logo: 'https://placehold.co/100x100.png', logoHint: 'torpedo logo' },
        score: '2-2',
        tournament: 'Moscow Open',
        game: 'Футбол',
        date: '2024-08-01',
        status: 'Завершен',
        href: '/matches/123',
        playgroundId: 'playground-1',
    },
    {
        id: '4',
        team1: { name: 'Дворовые Атлеты', logo: 'https://placehold.co/100x100.png', logoHint: 'athletic team logo' },
        team2: { name: 'Вымпел', logo: 'https://placehold.co/100x100.png', logoHint: 'pennant logo' },
        score: '5-2',
        tournament: 'Кубок Города',
        game: 'Футбол',
        date: '2024-08-03',
        status: 'Завершен',
        href: '/matches/123',
        playgroundId: 'playground-1',
    },
     {
        id: '5',
        team1: { name: 'Ледяные Волки', logo: 'https://placehold.co/100x100.png', logoHint: 'wolf logo' },
        team2: { name: 'Теневые Лисы', logo: 'https://placehold.co/100x100.png', logoHint: 'fox logo' },
        score: 'VS',
        tournament: 'Лига ProDvor',
        game: 'Valorant',
        date: '2024-08-05',
        status: 'Предстоящий',
        href: '/matches/123',
        playgroundId: null,
    },
    {
        id: '6',
        team1: { name: 'Дворовые Атлеты', logo: 'https://placehold.co/100x100.png', logoHint: 'athletic team logo' },
        team2: { name: 'Соколы', logo: 'https://placehold.co/100x100.png', logoHint: 'falcon logo' },
        score: '4-1',
        tournament: 'Товарищеский матч',
        game: 'Футбол',
        date: '2024-08-04',
        status: 'Завершен',
        href: '/matches/123',
        playgroundId: 'playground-1',
    },
    {
        id: '7',
        team1: { name: 'Дворовые Атлеты', logo: 'https://placehold.co/100x100.png', logoHint: 'athletic team logo' },
        team2: { name: 'Торпедо', logo: 'https://placehold.co/100x100.png', logoHint: 'torpedo logo' },
        score: '2-3',
        tournament: 'Товарищеский матч',
        game: 'Футбол',
        date: '2024-08-05',
        status: 'Завершен',
        href: '/matches/123',
        playgroundId: 'playground-1',
    },
    {
        id: '8',
        team1: { name: 'Соколы', logo: 'https://placehold.co/100x100.png', logoHint: 'falcon logo' },
        team2: { name: 'Вымпел', logo: 'https://placehold.co/100x100.png', logoHint: 'pennant logo' },
        score: '21-18',
        tournament: 'Товарищеский матч',
        game: 'Стритбол',
        date: '2024-08-06',
        status: 'Завершен',
        href: '/matches/123',
        playgroundId: 'playground-2',
    }
];

export type Match = (typeof matchesList)[0] & { playgroundId?: string | null };
