
export const teams = [
    {
        name: 'Кибер Орлы',
        motto: 'Высокий полет, точный удар',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'eagle logo',
        game: 'Valorant',
        rank: 1,
        members: 5,
        captain: 'Superuser',
        slug: 'cyber-eagles',
    },
    {
        name: 'Ледяные Волки',
        motto: 'Холодный расчет, яростная атака',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'wolf logo',
        game: 'CS:GO 2',
        rank: 2,
        members: 5,
        captain: 'ColdSniper',
        slug: 'ice-wolves',
    },
    {
        name: 'Теневые Лисы',
        motto: 'Скорость и хитрость',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'fox logo',
        game: 'Apex Legends',
        rank: 3,
        members: 3,
        captain: 'Foxy',
        slug: 'shadow-foxes',
    },
    {
        name: 'Стальные Титаны',
        motto: 'Несокрушимая оборона',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'titan logo',
        game: 'Dota 2',
        rank: 4,
        members: 5,
        captain: 'TheWall',
        slug: 'steel-titans',
    },
];
