
export const teams = [
    {
        name: 'Дворовые Атлеты',
        motto: 'Сила в единстве',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'athletic team logo',
        game: 'Футбол',
        rank: 1,
        members: 11,
        captain: 'Superuser',
        slug: 'dvotovyie-atlety',
    },
    {
        name: 'Соколы',
        motto: 'Высокий полет, точный удар',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'falcon logo',
        game: 'Баскетбол',
        rank: 2,
        members: 5,
        captain: 'ColdSniper',
        slug: 'sokoly',
    },
    {
        name: 'Торпедо',
        motto: 'Скорость и хитрость',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'torpedo logo',
        game: 'Хоккей',
        rank: 3,
        members: 6,
        captain: 'Foxy',
        slug: 'torpedo',
    },
    {
        name: 'Вымпел',
        motto: 'Несокрушимая оборона',
        logo: 'https://placehold.co/100x100.png',
        dataAiHint: 'pennant logo',
        game: 'Волейбол',
        rank: 4,
        members: 6,
        captain: 'TheWall',
        slug: 'vympel',
    },
];
