
export const userList = [
    {
        id: '1',
        name: 'Елена Иванова',
        email: 'elena@example.com',
        avatar: 'https://placehold.co/100x100.png',
        role: 'Игрок',
        status: 'Активен',
        profileUrl: '/users/1',
        activitySummary: 'Частые сообщения в чате, участие в 3 турнирах за последний месяц. Нет жалоб.',
        statsSummary: 'Играет в футбол, роль - Защитник. Спокойный стиль игры, хороший показатель отборов. Онлайн по вечерам.',
    },
    {
        id: '2',
        name: "Петр 'Beast' Сидоров",
        email: 'peter.s@example.com',
        avatar: 'https://placehold.co/100x100.png',
        role: 'Капитан',
        status: 'Активен',
        profileUrl: '/users/2',
        activitySummary: 'Высокая активность, лидер команды "Дворовые Атлеты". Была одна жалоба на грубую игру, но она была отклонена.',
        statsSummary: 'Играет в футбол, роль - Нападающий. Агрессивный капитан, много общается. Онлайн почти всегда.',
    },
    {
        id: '3',
        name: "Maria 'Shadow' Petrova",
        email: 'maria.p@example.com',
        avatar: 'https://placehold.co/100x100.png',
        role: 'Модератор',
        status: 'Активен',
        profileUrl: '/users/3',
        activitySummary: 'Обработала 50 жалоб за неделю. Активность в чате низкая. Высокий рейтинг от пользователей.',
        statsSummary: 'Играет в баскетбол в свободное время, роль - разыгрывающий. Низкая активность в матчах.',
    },
    {
        id: '4',
        name: 'Николай Васильев',
        email: 'nikolay.v@example.com',
        avatar: 'https://placehold.co/100x100.png',
        role: 'Судья',
        status: 'Активен',
        profileUrl: '/users/4',
        activitySummary: 'Провел судейство 10 матчей. Положительные отзывы от капитанов команд. Нет нарушений.',
        statsSummary: 'Не играет в соревновательные матчи, занимается судейством.',
    },
    {
        id: '5',
        name: 'Анна Кузнецова',
        email: 'anna.k@example.com',
        avatar: 'https://placehold.co/100x100.png',
        role: 'Игрок',
        status: 'Забанен',
        profileUrl: '/users/5',
        activitySummary: 'Пользователь был забанен за многократные нарушения правил сообщества. 3 предупреждения за неспортивное поведение.',
        statsSummary: 'Играет в волейбол, роль - связующий. Статистика недоступна из-за бана.',
    },
    {
        id: '6',
        name: 'Иван Смирнов',
        email: 'ivan.s@example.com',
        avatar: 'https://placehold.co/100x100.png',
        role: 'Организатор',
        status: 'Активен',
        profileUrl: '/users/6',
        activitySummary: 'Организовал 2 турнира. Высокая активность на платформе.',
        statsSummary: 'Играет в Футбол 5x5. Организует любительские матчи.',
    },
];
