   - name: Wait for Kong to be ready
     run: |
       echo "Waiting for Kong..."
       i=0
       until curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep -E "2..|4.."; do
         i=$((i+1))
         if [ $i -ge 30 ]; then
           echo "Kong failed to start in time."
           docker compose logs kong
           exit 1
         fi
         sleep 2
       done
       echo "Kong proxy ok"
